//! Generated API assembly bootstrap for sdkwork-shop.
//! Regenerated by pnpm api:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;
use std::sync::Arc;
use sdkwork_web_bootstrap::{ApiAssemblyContribution, ReadinessCheck};
use sdkwork_web_core::{DomainContextInjector, HttpRouteManifest};
use sdkwork_shop_service_host::ShopServiceHost;

pub type ApiAssembly = ApiAssemblyContribution;

pub struct ApiAssemblyContext {
    pub host: Arc<ShopServiceHost>,
    pub domain_context_injectors: Vec<Arc<dyn DomainContextInjector>>,
    pub readiness_check: Arc<dyn ReadinessCheck>,
}

pub async fn assemble_api_router(context: ApiAssemblyContext) -> Result<ApiAssembly, String> {
    let ApiAssemblyContext { host, domain_context_injectors, readiness_check } = context;
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_shop_app_api::gateway_mount_business(host.clone()));
    router = router.merge(sdkwork_routes_shop_backend_api::gateway_mount_business(host.clone()));
    let mut routes = Vec::new();
    routes.extend_from_slice(sdkwork_routes_shop_app_api::gateway_route_manifest().routes());
    routes.extend_from_slice(sdkwork_routes_shop_backend_api::gateway_route_manifest().routes());
    ApiAssemblyContribution::from_manifest(
        "sdkwork-shop",
        "SDKWork shop API",
        router,
        HttpRouteManifest::from_owned_routes(routes),
        domain_context_injectors,
        readiness_check,
    )
}

pub async fn assemble_app_api_contribution(context: ApiAssemblyContext) -> Result<ApiAssembly, String> {
    let ApiAssemblyContext { host, domain_context_injectors, readiness_check } = context;
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_shop_app_api::gateway_mount_business(host.clone()));
    let mut routes = Vec::new();
    routes.extend_from_slice(sdkwork_routes_shop_app_api::gateway_route_manifest().routes());
    ApiAssemblyContribution::from_manifest(
        "sdkwork-shop",
        "SDKWork shop App API",
        router,
        HttpRouteManifest::from_owned_routes(routes),
        domain_context_injectors,
        readiness_check,
    )
}

pub async fn assemble_backend_api_contribution(context: ApiAssemblyContext) -> Result<ApiAssembly, String> {
    let ApiAssemblyContext { host, domain_context_injectors, readiness_check } = context;
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_shop_backend_api::gateway_mount_business(host.clone()));
    let mut routes = Vec::new();
    routes.extend_from_slice(sdkwork_routes_shop_backend_api::gateway_route_manifest().routes());
    ApiAssemblyContribution::from_manifest(
        "sdkwork-shop",
        "SDKWork shop Backend API",
        router,
        HttpRouteManifest::from_owned_routes(routes),
        domain_context_injectors,
        readiness_check,
    )
}

