[package]
rust-version.workspace = true
name = "sdkwork-routes-shop-backend-api"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true


[lints]
workspace = true
[lib]
path = "src/lib.rs"

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
sdkwork_contract_service.workspace = true
sdkwork_shop_repository_sqlx.workspace = true
sdkwork_iam_context_service.workspace = true
sdkwork_shop_service_host.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-web-core.workspace = true
sdkwork-web-axum.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-iam-web-adapter.workspace = true
sdkwork-utils-rust.workspace = true
uuid = { workspace = true }
